---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/de2shrnx/personalfin.easi7.in/
    - /bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='db/' --exclude='error_log' --exclude='config/database.override.php' --exclude='config/pin.override.php' . $DEPLOYPATH
